### ISSUE TITLE
Définir la liste d'attributs d'un champignon

### ISSUE THREAD

**Issue by jflheureux** [19Inocybe63/Fungiquebec#1]
Il faut définir la liste complète des attributs possibles pour les champignons (famille, genre, pied, chapeau... ) dans leur ordre d'affichage.

**Comment by 19Inocybe63** [comment]
Salut Jeff,

Au début, il faut placer les autorités ; la classe, l’ordre, la famille, le genre et l’espèce sont toujours en italique.

Classe Basidiomycetes
Ordre Agaricales
Famille Amanitaceae
Amanita farinosa Schwein., Schr. Naturf. Ges. Leipzig 1: 79 (1822)

Nous pourrons revenir sur la présentation, mais l’essentiel de l’information est là. Aussi, si nous pouvions placer le nom français dans le titre de l’album se serait mieux:
Amanita farinosa / Amanite farineuse

Voici les rubriques

• Acanthophyses
• Aiguillons
• Aleurioconidies
• Anamorphe
• Anamorphe conidien
• Anneau
• Apothécie
• Arête lamellaire
• Arthroconidies
• Ascome
• Ascospores
• Asques
• Astérohyphidies
• Auteur de la description
• Base du pied
• Base stérile
• Base stipitiforme
• Basides
• Basidiospores
• Basidioles
• Basidiome
• Bibliographies
• Biotopes
• Boucles
• Brachybasidioles
• Calicule
• Capillitium
• Capitule
• Caulobasides
• Caulocystides (Dermatocystides)
• Caulocystides médianes
• Caulocystides sommitales
• Cellules hyméniales diverticulées
• Cellules hyméniales en brosses
• Cellules marginales (Paracystides)
• Cellules périthéciales
• Cellules stromatiques
• Chair
• Chancre
• Chapeau
• Cheilocystides
• Cheilomacrocystides
• Chlamydospores
• Chrysocystides
• Circumcystides
• Clavules
• Columelle
• Comestibilité
• Commentaires
• Conidies
• Conidiome
• Conidiophores
• Consistance
• Contexte
• Cordons mycéliens
• Cordons rhizomorphiques
• Cortex
• Cortex caulinaire
• Cortex du pied et du bulbe
• Cortex péridial
• Cortex sclérotial
• Cortine
• Couche(s) de tubes
• Coupe stérile
• Cristaux
• Cristaux d’oxalate
• Cuticule
• Cutis
• Cycle
• Cystides
• Cystides hyméniales
• Cystides intermédiaires
• Cystidioles
• Dendrohyphydies
• Dépôts de pigment interhyphal
• Dermatocystides (Caulocystides et Pileipellis)
• Dernière correction
• Dicaryophyses
• Dichophyses
• Disque basal
• Distribution et abondance
• Élatères
• Éléments acanthophyses
• Éléments cystidioïdes
• Éléments hyphoïdes
• Éléments sétoïdes
• Éléments stériles
• Éléments sur les côtés
• Éléments vélaires
• Endopéridium
• Espèces Identification
• Espèces semblables
• Excipulum
• Excipulum médullaire supérieur
• Excipulum médullaire moyen
• Excipulum médullaire inférieur
• Excipulum ectal
• Exhalaison
• Exopéridium
• Face externe
• Face poroïde
• Feutrage basal
• Fragments sporaux
• Fréquence
• Glèbe
• Gléocystides
• Gléocystides hyméniales
• Gléocystides subhyméniales
• Granules calcaires
• Groupe
• Hyménium
• Hyménocystides (Cheilocystides et Pleurocystides)
• Hyménophore
• Hyphes
• Hyphes de la chair
• Hyphes de l’anneau
• Hyphes du pied
• Hyphes glébales
• Hyphes gléoplères
• Hyphes hyméniales
• Hyphes ligatives
• Hyphes oléifères
• Hyphes pectinées
• Hyphes primordiales
• Hyphes sétales
• Hyphes squelettiques
• Hyphes skeletoligative
• Hyphes subiculaires
• Hyphes tramales
• Hyphes vésiculaires
• Hyphidies
• Hyphique
• Hypobasides
• Hypoderme
• Hypogé
• Hypophylle
• Hypothalle
• Hypothèce
• Hystérothèce
• Lames
• Lamprocystides
• Lamprocheilocystides
• Lampropleurocystides
• Lamprocaulocystides
• Latex
• Leptocystides
• Macrocystides
• Macropleurocystides
• Marge
• Marge et face externe
• Médiostrate
• Medulla
• Medulla caulinaire
• Medulla clavariale
• Medulla clavulaire
• Microconidies
• Mode de croissance
• Mycélium basal
• Myxocarpe
• Note taxonomique
• Œuf
• Paracapillitium
• Paraphyses
• Parasite
• Paroi périthéciale
• Péridiole
• Péridiopellis
• Péridium
• Période d’observation
• Périthèces
• Phialoconidies
• Pied
• Pieds stériles
• Pigments
• Pileipellis
• Pileitrame
• Pileocystides (Dermatocystides)
• Plasmode
• Pleurocystides (Hyménocystides)
• Poils
• Poils basaux
• Poils caulinaires
• Poils du cortex
• Poils externes
• Poils latéraux et caulinaires
• Poils marginaux
• Poils mycélien basaux
• Poils péridiaux
• Poils périthéciaux
• Poils piléiques
• Pores
• Pseudocapillitium
• Pseudocolumelle
• Pseudocystides
• Pseudo péridioles
• Réactions chimiques
• Réceptacle
• Remarques
• Rhizomorphes
• Sac sporifère
• Sclérocystides
• Sclérote
• Soies
• Soies hyméniales
• Sporée
• Spores
• Sporocystes
• Stipitipellis
• Stipititrame
• Stroma
• Subhyménium
• Subiculum
• Substrat
• Système hyphal
• Textura
• Tomentum caulinaire
• Tomentum piléique
• Trame hyménophorale
• Trame lamellaire
• Trame tubulaire
• Type
• Typique
• Voile
• Voile général
• Voile partiel
• Volve
• Zone périhyméniale

Claude

**Comment by 19Inocybe63** [comment]
J'ai oublié ce terme : •	Sphérocytes

**Comment by 19Inocybe63** [comment]
Il faut ajouter le terme suivant : Acanthocytes
