### ISSUE TITLE
Description de Amanita farinosa

### ISSUE THREAD

**Issue by 19Inocybe63** [19Inocybe63/Fungiquebec#2]
Voici maintenant la description:

Chapeau 25-65 mm Ø; hémisphérique au début, devenant convexe à presque étalé, sec, gris, couvert à la surface d’une couche poudreuse de restes vélaires brun grisâtre, glabre ;
Lames libres à adnexées, avec lamellules tronquées, serrées, blanchâtres à grisâtre ;
Pied 30-90 x 3-10 mm Ø, cylindrique plus ou moins égale, bulbeux non marginé, glabre à poudreux, blanchâtre, glabre à légèrement soyeux, solide ou partiellement creux à maturité ;
Voile général friable, gris-brun, laissant une couche poudreuse sur le chapeau ;
Voile partiel absent ;
Chair blanche immuable ;
Odeur indistincte ;
Saveur indistincte ;
Sporée blanche ;
Basides claviformes, tétrastérigmates, non bouclées à la base, 30-33 x 8-10 µm en moyenne ;
Spores subglobuleuses à elliptiques vue de profil, largement elliptiques vue frontale, lisses, à paroi mince, avec appendice hilaire, à contenu uniguttulé, hyalines avec reflet verdâtre en NaCl isotonique 0,9 %, inactives en melzer, cyanophiles
7,6 [8,2; 8,5] 9,1 x 5,9 [6,3; 6,5] 6,9 µm
Q = 1,2 [1,3] 1,4; N = 30; C = 95%
Me = 8,3 x 6,4 µm; Qe = 1,3
Trame lamellaire bilatérale avec subhyménium à cellules renflées ;
Cheilocystides absentes ;
Pleurocystides absentes ;
Caulocystides absentes, plutôt des hyphes terminaux ;
Pileipellis en cutis et parfois en ixocutis, formé d’hyphes de 2-8 μm Ø ;
Voile partiel constitué d’hyphes filamenteux et des cellules sphérocytes ;

**Comment by 19Inocybe63** [comment]
J'aimerais qu'il puisse y avoir une petite séparation entre la macromorphologie et la microscopie.

**Comment by jflheureux** [comment]
Je ne sais pas ce qui est de la macromorphologie et de la microscopie dans tes attributs. Est-ce déjà correct avec la séparation actuelle ou bien il faut faire des changements?

**Comment by 19Inocybe63** [comment]
Avec le temps, je me suis habitué à voir l'information arrivée dans l'ordre habituel, celle de Funga Nordica (FN). La séparation entre macro et micro n'est donc plus nécessaire, car les rubriques sont très claires et défilent toujours selon l'ordre de description scientifique de FN ; donc, tout est en ordre.
