### ISSUE TITLE
Remplacer toutes les liens "originale" des planches

### ISSUE THREAD

**Issue by jflheureux** [19Inocybe63/Fungiquebec#24]
Tous les liens "originale" de toutes les planches sont des liens vers l'album du champignon. Il faut que ce soit des liens vers la grosse photo de la planche sur Flickr.

Format: https://www.flickr.com/photos/kaufholtz/XXXXXXXXXX/in/album-XXXXXXXXXXXXX/

**Comment by 19Inocybe63** [comment]
Correction terminée
