### ISSUE TITLE
Mesures sporales - les spores

### ISSUE THREAD

**Issue by 19Inocybe63** [19Inocybe63/Fungiquebec#3]
Il y a un problème avec les mesures des spores de Gymnopilus humicola. Lorsque j'ajoute les mesures, le site n'affiche plus rien, comme hier avec les deux points. J'ai enlevé les mesures et de fait rétabli le fonctionnement. Je suis donc certain que le petit bogue vient de la formulation des mesures des spores dont voici le texte:

7,1 [8; 8,4] 9,3 x 4,6 [5; 5,1] 5,5 µm
Q = 1,5 [1,6] 1,7; N = 30; C = 95%
Me = 8,2 x 5,1 µm; Qe = 1,6

La formulation de la mesure sporale ci-dessus ne peut pas être changée ; elle se présente toujours ainsi dans les monographies, c'est un standard.

Pour le reste des informations, tout fonctionne parfaitement. Par contre, je ne sais plus comment mettre en ordre alphabétique les différentes rubriques.

**Comment by 19Inocybe63** [comment]
Ok, j'ai placé la mesure en continu et non plus sur trois lignes, et ça fonctionne.

**Comment by jflheureux** [comment]
C'est arrangé. La syntaxe est:
attribut: |
  ligne1
  ligne2
  ...
