### ISSUE TITLE
In english

### ISSUE THREAD

**Issue by 19Inocybe63** [19Inocybe63/Fungiquebec#33]
Est-ce possible de réaliser une page en anglais de: À propos ? Cette page inclurait aussi l'auteur.
Les gens n'auraient qu'à sélectionner un petit lien à droite indiquant: In english
Notre thème le permet-il ?

**Comment by jflheureux** [comment]
Notre thème ne le permet pas officiellement mais ce serait réalisable assez facilement. Je vais m'en occuper.
