### ISSUE TITLE
Diminution du trait dans les détails

### ISSUE THREAD

**Issue by 19Inocybe63** [19Inocybe63/Fungiquebec#5]
Dans les détails, il faudrait diminuer le trait entre les rubriques. Sinon, la photo (vignette) est trop basse, on ne le voit pas à l'ouverture de la page.

**Comment by jflheureux** [comment]
Ça va toujours dépendre de l'écran que le visiteur utilise. S'il est sur une tablette ou un téléphone, combien même qu'on diminue le trait, la photo ne sera pas visible sans défiler vers le bas.

À toi de me dire ce qui est plus important: Les détails ou la photo?

Je vais mettre le plus important en haut de cette colonne.
